optimize creating fake data and add scripts for acceptance

diff --git a/bin/acceptance b/bin/acceptance
--- a/bin/acceptance
+++ b/bin/acceptance
@@ -1,26 +1,42 @@
 #!/usr/bin/env bash
+set -e
+# 120586240 = 100 mb + 15%
+if [ $# -ne 1 ];then
+    echo "You need to pass a file size in bytes as first argument."
+    exit 1
+fi
 BASEDIR=$(dirname $0)
 service_name="db-dumper-service-acceptance"
-fileurl="https://media.githubusercontent.com/media/ArthurHlt/worldcities-database/master/worldcities_100mb.sql"
-filepath="worldcities_100mb.sql"
+filepath="fakedata_$1.sql"
+WD=`pwd`
+mysql_bin_path="${WD}/src/main/resources/binaries/mysql/bin/mysql"
+push_data_app_dir="${BASEDIR}/acceptance_app/push_data"
+push_data_app_name="db-dumper-push-data"
 
+jq_path="jq"
+hash mysql 2>/dev/null || { echo "Mysql is required to run acceptance test"; exit 1; }
+hash jq 2>/dev/null || { echo "Installing jq"; $BASEDIR/install_jq; jq_path="./jq"; }
+
+if [ ! -f "$mysql_bin_path" ]; then
+    echo "Please install binaries for mysql first (You can use bin/install-binaries)"
+    exit 1
+fi
 
 if [ ! -f "$filepath" ]; then
-    echo "Downloading sample sql..."
-    if hash curl 2>/dev/null; then
-        RESPONSE=$(curl --write-out %{http_code} -L -o "${filepath}" "$fileurl")
-    else
-        wget -o "${filepath}" "$fileurl"
-        RESPONSE=$?
-    fi
-    if [ "$RESPONSE" != "200" ] && [ "$RESPONSE" != "0" ]; then
-        echo "File ${fileurl} not found, so it can't be downloaded."
-        rm "$filepath"
-        exit 1
-    fi
-    echo "Download is finished."
+    echo "Creating fake data..."
+    $BASEDIR/create_fake_data "$1" "$filepath"
+    echo "Fake data have been created."
     echo ""
 fi
+
+get_push_data_state () {
+    if hash curl 2>/dev/null; then
+        `curl $1 &> /dev/null`
+    else
+        `wget -O - "$1" &> /dev/null`
+    fi
+    return "$?"
+}
 
 echo "Deploying db-dumper-service..."
 $BASEDIR/deploy
@@ -33,6 +49,96 @@ source $BASEDIR/user
 cf create-service-broker $service_name myUs3r myPasssw0rd $SERVICE_URL
 cf enable-service-access db-dumper-service -o $AVAILABLE_ON_ORG
 echo "Registered."
+echo ""
+
+echo "Creating service source database..."
+cf cs p-mysql 100mb source_db_dumper_acceptance
+cf create-service-key source_db_dumper_acceptance mykey
+echo "Created."
+echo ""
+
+echo "Creating service target database..."
+cf cs p-mysql 100mb target_db_dumper_acceptance
+cf create-service-key target_db_dumper_acceptance mykey
+echo "Created."
+echo ""
+
+echo "Pushing data in source database..."
+rm -f "$push_data_app_dir"/fakedata*
+cp "$mysql_bin_path" "$push_data_app_dir"
+cp "$filepath" "$push_data_app_dir"
+service_value=`cf service-key source_db_dumper_acceptance mykey | awk 'FNR > 1'`
+
+port=`echo $service_value | $jq_path '.port'`
+hostname=`echo $service_value | $jq_path .hostname`
+database_name=`echo $service_value | $jq_path .name`
+username=`echo $service_value | $jq_path .username`
+password=`echo $service_value | $jq_path .password`
+uri_database_source=`echo $service_value | $jq_path .uri`
+cf push "$push_data_app_name" -p "$push_data_app_dir" -b php_buildpack --no-manifest -c "\$HOME/htdocs/push_data $hostname $port $username $password $database_name $filepath & .bp/bin/start"
+
+app_url=`cf a | awk -v search="$push_data_app_name" '$0 ~ search { print $6 }'`
+i="0"
+while true
+do
+    get_push_data_state "$app_url"
+    state=$?
+    if [ "$state" != "0" ]; then
+        break
+    fi
+    if (( $i % 3 == 0 ))
+    then
+         printf "\rPushing.  "
+    elif (( $i % 3 == 1 )); then
+        printf "\rPushing.. "
+    elif (( $i % 3 == 2 )); then
+        printf "\rPushing..."
+    fi
+    i=$(( $i + 1 ))
+    sleep 1
+done
+
+if [ "$state" != "1" ]; then
+    echo "Error occurred when pushing data:"
+    echo "$state"
+    exit 1
+fi
+echo "Data have been pushed."
+echo ""
+
+exit 0
+
+echo "Deleting service source database..."
+cf delete-service-key source_db_dumper_acceptance mykey -f
+cf ds source_db_dumper_acceptance -f
+echo "Deleted."
+echo ""
+
+echo "Deleting service target database..."
+cf delete-service-key target_db_dumper_acceptance mykey -f
+cf ds target_db_dumper_acceptance -f
+echo "Deleted."
+echo ""
+# cf delete-service-broker db-dumper-service-acceptance -f
+echo "Unregistering db-dumper-service as a service..."
+$BASEDIR/target
+source $BASEDIR/user
+cf delete-service-broker $service_name -f
+echo "Unregistered."
+echo ""
+
+exit 0
+
+echo "Dumping with db-dumper-service"
+cf cs db-dumper-service experimental acceptance_test -c '{"src_url":"${uri_database_source}"}'
+echo "Dump finished."
+echo ""
+
+echo "Restoring in target database"
+service_value=`cf service-key source_db_dumper_acceptance mykey | awk 'FNR > 1'`
+uri_database_target=`echo $service_value | $jq_path '.uri'`
+cf update-service acceptance_test -c '{"src_url":"${uri_database_source}", "target_url": "${uri_database_target}", "action": "restore"}'
+echo "Restore finished."
 echo ""
 
 echo "Unregistering db-dumper-service"
